name = "my-rss-generator"
main = "index.js"
compatibility_date = "2023-10-25"

# 启用 Node.js 兼容性标志以支持 cheerio 等库
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "echo 'No build step required for this worker'"

# 如果你有环境变量，可以在这里定义
# [vars]
# MY_VAR = "my-value"
