name = "my-rss-generator"
main = "index.js"
# 更新 compatibility_date 以解决 string_decoder 问题
compatibility_date = "2024-09-23"

# 确保 Node.js 兼容性标志已设置，以支持 cheerio
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "echo 'No build step required for this worker'"

# 如果你有环境变量，可以在这里定义
# [vars]
# MY_VAR = "my-value"
