# wrangler.toml
name = "my-rss-generator" # 你的 Worker 名称，可以修改
main = "index.js"         # 关键：指定入口文件是 index.js
compatibility_date = "2023-10-25" # 使用一个较新的兼容日期

[build]
command = "echo 'No build step required for this worker'"
